tracer.property : "I AM THE DEV"
spring:
  jpa:
    database: "MYSQL"
    show-sql: "true"
    properties:
      hibernate:
        dilect: "org.hibernate.dialect.MySQLDialect"
  datasource:
    platform: "mysql"
    url: "jdbc:mysql://localhost:3306/dev?useSSL=false"
    username: "root"
    password: "{cipher}b4aae6f562baccc7d308fae300b388fc71cd7a18dcd79e46188b636f4d51e7f4"
    driver-class-name: "com.mysql.jdbc.Driver"
